repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: alejandra
        name: alejandra
        entry: alejandra
        files: \.nix$
        language: system
        stages: [pre-commit]
