os: osx
osx_image: xcode9.3
jdk:
- oraclejdk8
script:
- jdk_switcher use oraclejdk8
- java -version
- sed -i '' '/mas "/s/^/#/g' Brewfile
- git diff
- rm -rf /usr/local/Cellar/*
- brew prune
- brew config
- brew update
- brew bundle
